global:
  images:
    tags:
      tf_operator: atsgen/tf-operator:v0.0.1
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password
  contrail_env:
    CONTAIN45ER_REGISTRY: docker.io/opencontrailnig 
networking:
  ipFabricSubnet: 10.64.0.0/12
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
