apiVersion: tungsten.atsgen.com/v1alpha1
kind: SDN
metadata:
  name: default
spec:
  cniConfig:
    clusterName: k8s
    ipFabricNetwork:
      cidr: {{ .Values.networking.ipFabricSubnet }}
    podNetwork:
      cidr: {{ .Values.networking.podSubnet }}
    serviceNetwork:
      cidr: {{ .Values.networking.serviceSubnet }}
    ipForwarding: snat
    useHostNewtorkService: true
  datapathConfig:
    useVrouter: true
