kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRoleBinding }}
subjects:
- kind: ServiceAccount
  name: tf-operator
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: tf-operator
  apiGroup: rbac.authorization.k8s.io
---
